config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  get 'privacy' => 'main#privacy'
  get 'terms-and-conditions' => 'main#terms', as: "terms"
  get 'pay-if-you-like' => "main#pay_if_you_like"

  post 'order' => 'order#initiate'
  get 'order' => 'order#index'

  post 'upload' => 'order#upload'

  get 'blog' => 'blog#index'
  match 'blog/:slug' => 'blog#show', as: 'show_post', via: :get

  post 'contact' => 'contact#index'

  devise_for :accounts
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @posts = Post.order(updated_at: :desc).page params[:page]
    @page_title = 'OwnEssays.com | Blog'
    @page_title += " - Page #{params['page']}" if params[:page].present?
  end

  def show
    @post = Post.find_by_slug(params[:slug])
    @page_title = @post.title if @post
    @non_ajax = !request.xhr?
    render :layout => @non_ajax
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/index.html.erb
<div id="page-wrapper" class="bg-blue-dark dark" data-scroll-easing="easeOutBack">

  <div class="posts-list">

    <% colors = %w(bg-green bg-orange bg-red bg-blue bg-purple bg-green bg-orange bg-red bg-blue bg-purple) %>
    <% if @posts.count > 0 %>
        <% @posts.each_with_index do |post, index| %>
            <!-- Post - Section -->
            <div class="post section <%= colors[index] %> dark" data-header-change="true">

              <div class="image">
                <div class="bg-image">
                  <%= image_tag post.photo %>
                </div>
              </div>

              <div class="content">
                <div class="meta">
                  <span><i class="fa fa-clock-o"></i><%= post.updated_at.strftime("%B %d, %Y") %></span>
                  <span><i class="fa fa-tag"></i><%= post.category %></span>
                  <span><i class="fa fa-user"></i><%= post.author %></span>
                </div>
                <h1>
                  <%= link_to raw(post.title), show_post_path(post), data: { target: "ajax-modal"} %>
                </h1>

                <p>
                  <%= raw post.subtitle %>
                </p>

                <%= link_to "Read more",
                            show_post_path(post),
                            data: { target: "ajax-modal"},
                            class: "link-default" %>
              </div>

            </div>
            <!-- Post - Section / End -->
        <% end %>


    <% else %>

    <% end %>

  </div>

  <%= paginate @posts %>

  <!-- Footer -->
  <footer id="footer" class="bg-blue-dark padding-v-40 dark text-center">
    <div class="section-content copyright margin-b-20">
      Copyright <strong>OwnEssays.com</strong> 2018 ©. Made with love by <a
    href="http://phar.media"><strong>phar:media</strong></a>
    </div>
        <span data-target="local-scroll"><a href="#section01" class="back-to-top"><i
        class="fa fa-chevron-up"></i></a></span>
  </footer>
  <!-- Footer / End -->

</div>

<%= render 'shared/sidebar' %>

<%= render 'shared/order_form_modal' %>

app/views/blog/show.html.erb
<!-- Page Wrapper -->
<div id="page-wrapper" class="bg-blue-dark dark padding-t-130" data-scroll-easing="easeOutBack">

  <!-- @post.-->
  <div class="@post.container">
    <!--<div class="row margin-b-40">
      <div class="col-md-8 col-sm-10">
        <%= image_tag @post.photo(:headline) %>
      </div>
    </div>-->
    <div class="row">
      <div class="col-lg-8 col-sm-9 col-sm-offset-1">
        <div class="meta">
          <span><i class="fa fa-clock-o"></i><%= @post.updated_at.strftime("%B %d, %Y") %></span>
          <span><i class="fa fa-tag"></i><%= @post.category %></span>
          <span><i class="fa fa-user"></i><%= @post.author %></span>
        </div>
        <div class="@post.content margin-b-80">
          <h1><%= raw @post.title %></h1>

          <p class="lead">
            <%= raw @post.subtitle %>
          </p>

          <p>
            <%= raw @post.content %>
          </p>

        </div>
        <!-- Comments -->
      </div>
    </div>
  </div>

  <% if @non_ajax %>
      <!-- Footer -->
      <footer id="footer" class="bg-blue-dark padding-v-40 dark text-center">
        <div class="section-content copyright margin-b-20">
          Copyright <strong>OwnEssays.com</strong> 2016©. Made with love by <a
        href="http://phar.media"><strong>phar:media</strong></a>
        </div>
        <span data-target="local-scroll"><a href="#section01" class="back-to-top"><i
        class="fa fa-chevron-up"></i></a></span>
      </footer>
      <!-- Footer / End -->
  <% else %>
      <!-- Close -->
      <a href="#" class="ajax-close x-close" data-dismiss="close"></a>
  <% end %>

</div>
<!-- Page Wrapper / End -->